package io.mindspice.databaseservice.client.endpoints;

public enum GameEndpoint implements Endpoint{
    GET_PAWN_SETS,
    UPDATE_PAWN_SET,
    DELETE_PAWN_SET,
    GET_POTION_TOKEN_AMOUNT,
    GET_PLAYER_FUNDS,
    COMMIT_POTION_PURCHASE,
    COMMIT_POTION_USE,
    COMMIT_MATCH_RESULT,
    COMMIT_PLAYER_REWARDS,
    GET_PLAYER_DAILY_RESULTS,
    GET_PLAYER_HISTORICAL_RESULTS,
    GET_PLAYER_CARDS,
    GET_PLAYER_DISPLAY_NAME,
    UPDATE_PLAYER_DISPLAY_NAME,
    UPDATE_PLAYER_AVATAR,
    GET_LAST_DID_UPDATE,
    GET_LAST_AVATAR_UPDATE,
    GET_LAST_DISPLAY_NAME_UPDATE,
    IS_VALID_DID_LAUNCHER,
    GET_PLAYER_INFO,
    GET_PLAYER_DID,
    DOES_NAME_EXIST,
    GET_REWARDS_FOR_DISPERSAL,
    GET_ACCOUNT_COIN,
    RESET_DAILY_RESULTS,
    COMMIT_FULL_MATCH_RESULT,
    ADD_FLAGGED_DISPERSAL,
    GET_FREE_GAMES_PLAYED,
    ADD_FREE_GAME_PLAYED,
    RESET_FREE_GAMES_PLAYED,
    ADD_FAILED_TRANSACTION,
    ADD_PACK_REDEMPTION,
    GET_MATCH_RESULTS;



    @Override
    public String getPath() {
        return "/game/" + name().toLowerCase();
    }
}
